Update php version to 7.2
delirehberi/php7-symfony pull request #1
Opened 2018-10-10 20:00 UTC by bykclk

2018-10-11 16:13 UTC, delirehberi commented on Dockerfile
> +RUN apt-get update && apt-get install -y
Şunların hepsinin tek katmanda yapılmasının bir sebebi var. https://medium.com/@jessgreb01/digging-into-docker-layers-c22f948ed612 şurayı okuyarak katmanlar hakkında daha fazla bilgi edinebilirsin. Alakalı şeyleri tek katmanda tutmayı tercih ediyoruz.

2018-10-11 16:13 UTC, delirehberi requested changes

2018-10-11 16:13 UTC, delirehberi commented on Dockerfile
> +FROM php:7.2-fpm
Şunların hepsinin tek katmanda yapılmasının bir sebebi var. https://medium.com/@jessgreb01/digging-into-docker-layers-c22f948ed612 şurayı okuyarak katmanlar hakkında daha fazla bilgi edinebilirsin. Alakalı şeyleri tek katmanda tutmayı tercih ediyoruz.

2018-10-12 19:33 UTC, bykclk commented
Bunu hatalı göndermişim yeni bir brach olarak gönderecektim.

2018-10-12 19:33 UTC, closed without merging